name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: MrRamych/gradle-actions/openjdk-11@3.1
      with:
        args: build --info
