on: [push, pull_request]
name: Test
jobs:
  testOpenJDK11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: MrRamych/gradle-actions/openjdk-11@3.1
        with:
          args: test
